# Generated by Django 4.2.16 on 2024-11-20 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_profile_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_img',
            field=models.ImageField(default='image/profile.png', upload_to='image/'),
        ),
    ]
