# Generated by Django 4.2.16 on 2024-11-21 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankmap', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FinMapToken',
        ),
        migrations.AddField(
            model_name='bankbranch',
            name='bank_code',
            field=models.CharField(blank=True, choices=[('004', '국민은행'), ('011', '농협은행'), ('020', '우리은행'), ('081', '하나은행')], max_length=3, null=True),
        ),
    ]
