# Generated by Django 4.2.16 on 2024-11-24 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finlife', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='savingoptions',
            name='rsrv_type_nm',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
